# Generated by Django 5.2.5 on 2025-09-08 23:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroUserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astro_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=191, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('wiki_html', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AstroCommunitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astro_summary', to='core.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p95_votes_5m', models.FloatField(default=0)),
                ('p95_votes_15m', models.FloatField(default=0)),
                ('p10_comments_per_100_upvotes', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='core.community')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('text', 'text'), ('link', 'link'), ('image', 'image')], max_length=10)),
                ('title', models.CharField(max_length=140)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=191)),
                ('content_url', models.CharField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('link_domain', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='posts/thumbs/')),
                ('score', models.IntegerField(default=0)),
                ('hot_rank', models.FloatField(db_index=True, default=0)),
                ('rising_rank', models.FloatField(db_index=True, default=0)),
                ('controversy', models.FloatField(db_index=True, default=0)),
                ('best_rank', models.FloatField(db_index=True, default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('slowmode', models.PositiveIntegerField(default=0)),
                ('domain_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.community')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('voter_age_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, db_index=True, default='')),
                ('body', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='AstroScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate5', models.IntegerField(default=0)),
                ('rate15', models.IntegerField(default=0)),
                ('early_new_share', models.FloatField(default=0)),
                ('discuss_ratio', models.FloatField(default=0)),
                ('score', models.IntegerField(default=1)),
                ('severity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astro_scores', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astro_scores', to='core.community')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astro_score', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostBurstState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buckets', models.JSONField(default=list)),
                ('bucket_index', models.PositiveSmallIntegerField(default=0)),
                ('bucket_span_seconds', models.PositiveIntegerField(default=60)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_5m', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burst_state', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_links', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('is_note', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_cached', models.IntegerField(db_index=True, default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'post'), ('comment', 'comment')], max_length=10)),
                ('target_id', models.PositiveBigIntegerField()),
                ('value', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_community_name_ci'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at', '-id'], name='core_post_communi_935b52_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='post_comm_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-hot_rank', '-created_at'], name='core_post_hot_ran_362496_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-score', '-created_at'], name='core_post_score_b8ea5f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-controversy', '-created_at'], name='core_post_controv_e9ce9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('community', 'slug'), name='uniq_post_community_slug'),
        ),
        migrations.AddIndex(
            model_name='engagementevent',
            index=models.Index(fields=['post', '-created_at'], name='core_engage_post_id_cfa9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementevent',
            index=models.Index(fields=['created_at'], name='core_engage_created_78c1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'path'], name='core_commen_post_id_3e9299_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comment_post_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitcounter',
            unique_together={('user', 'action')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='core_report_content_93408d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ['post', 'comment'])), name='vote_valid_target_type'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='uniq_vote_user_target'),
        ),
    ]
