# Generated by Django 4.2 on 2025-08-18 04:39

from django.db import migrations, models
import math
from django.utils import timezone


def recompute(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    now = timezone.now()
    for post in Post.objects.all():
        age_hours = max((now - post.created_at).total_seconds() / 3600, 0.5)
        hot = post.score / math.pow(age_hours + 2, 1.8)
        post.hot_rank = hot
        post.save(update_fields=["hot_rank"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_comment_parent_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hot_rank",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.RunPython(recompute, migrations.RunPython.noop),
    ]
