# Generated by Django 5.2.5 on 2025-09-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
