# Generated by Django 4.2.5 on 2025-08-19 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_post_hot_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_cached", models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="core_post_communi_9f66d4_idx",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="path",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AddField(
            model_name="community",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communities",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(default="temp", max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="best_rank",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="controversy",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="rising_rank",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="target_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "path"], name="core_commen_post_id_3e9299_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["community", "-created_at", "-id"],
                name="core_post_communi_935b52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-hot_rank", "-created_at"], name="core_post_hot_ran_362496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-score", "-created_at"], name="core_post_score_b8ea5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-controversy", "-created_at"],
                name="core_post_controv_e9ce9b_idx",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
