# Generated by Django 4.2.5 on 2025-08-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_remove_post_core_post_communi_9f66d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='wiki_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
