# Generated by Django 5.2.5 on 2025-08-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_recoverycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("text", "text"), ("link", "link"), ("image", "image")],
                max_length=10,
            ),
        ),
    ]
