# Generated by Django 5.2.5 on 2025-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_post_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_thumb",
            field=models.ImageField(blank=True, null=True, upload_to="posts/thumbs/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
