# Generated by Django 5.2.5 on 2025-08-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_post_deleted_at_post_deleted_by_post_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
