# Generated by Django 5.2.5 on 2025-08-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_comment_edited_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostBurstState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buckets", models.JSONField(default=list)),
                ("bucket_index", models.PositiveSmallIntegerField(default=0)),
                ("bucket_span_seconds", models.PositiveIntegerField(default=60)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burst_state",
                        to="core.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EngagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_events",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "-created_at"],
                        name="core_engage_post_id_cfa9fe_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_engage_created_78c1fa_idx"
                    ),
                ],
            },
        ),
    ]
