# Generated by Django 5.2.5 on 2025-08-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_postburststate_engagementevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p95_votes_5m", models.FloatField(default=0)),
                ("p95_votes_15m", models.FloatField(default=0)),
                ("p10_comments_per_100_upvotes", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline",
                        to="core.community",
                    ),
                ),
            ],
        ),
    ]
