# Generated by Django 5.2.5 on 2025-08-31 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_postburststate_engagementevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementevent",
            name="voter_age_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postburststate",
            name="total_5m",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postburststate",
            name="window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
