# Generated by Django on 2024-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_communitybaseline"),
        ("core", "0016_engagementevent_voter_age_days_and_more"),
    ]

    operations = []
