# Generated by Django 5.2.5 on 2025-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0017_merge_0016_communitybaseline_0016_engagementevent_voter_age_days_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="url",
        ),
        migrations.AddField(
            model_name="post",
            name="content_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="heading",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="link_domain",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
