# Generated by Django 5.2.5 on 2025-09-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_post_url_post_content_url_post_embed_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
