# Generated by Django 5.2.5 on 2025-09-04 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_vote_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="uniq_vote_post_user",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="uniq_vote_comment_user",
        ),
        migrations.AlterField(
            model_name="astrocommunitysummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="astrousersummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "target_type", "target_id"),
                name="uniq_vote_user_target",
            ),
        ),
    ]
