# Generated by Django 5.2.5 on 2025-09-05 10:53

from django.db import migrations


def drop_embed_html(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    columns = [
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            cursor, "core_post"
        )
    ]
    if "embed_html" in columns:
        schema_editor.execute("ALTER TABLE core_post DROP COLUMN embed_html")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_comment_soft_delete"),
    ]

    operations = [
        migrations.RunPython(drop_embed_html, migrations.RunPython.noop),
    ]

