# Generated by Django 5.2.5 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_comment_soft_delete"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_post ADD COLUMN IF NOT EXISTS embed_html text",
            reverse_sql="ALTER TABLE core_post DROP COLUMN IF EXISTS embed_html",
            state_operations=[
                migrations.AddField(
                    model_name="post",
                    name="embed_html",
                    field=models.TextField(blank=True, default="", null=True),
                ),
            ],
        ),  # IF NOT EXISTS/IF EXISTS make this migration idempotent
    ]
