# Generated by Django 5.2.5 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_comment_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="embed_html",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
