# Generated by Django 5.2.5 on 2025-09-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_post_embed_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="embed_html",
        ),
    ]
