# Generated by Django 5.2.5 on 2025-09-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_drop_embed_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail_alt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
    ]
