# Generated by Django 5.2.5 on 2025-09-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_add_link_thumbnails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="embed",
        ),
        migrations.DeleteModel(
            name="Embed",
        ),
    ]
