# Generated by Django 5.2.5 on 2025-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_post_embed_html"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE core_post DROP COLUMN IF EXISTS embed_html",
                    "ALTER TABLE core_post ADD COLUMN embed_html text",
                )
            ],
            state_operations=[],
        )
    ]
