# Generated by Django 5.2.5 on 2025-09-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_post_embed_delete_embed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbnail_alt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="thumbnail_url",
        ),
    ]
