# Generated by Django 5.2.5 on 2025-09-08 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031a_populate_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=191),
        ),
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.SlugField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_url",
            field=models.CharField(
                blank=True,
                max_length=2048,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=140),
        ),
    ]
