# Generated by Django 5.2.5 on 2025-09-08 04:33

from django.conf import settings
from django.db import migrations
from django.db.models.functions import Length
from django.utils.text import slugify


def check_lengths(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    Community = apps.get_model("core", "Community")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    if Post.objects.annotate(l=Length("title")).filter(l__gt=140).exists():
        raise RuntimeError("Post.title longer than 140 characters")
    if Post.objects.annotate(l=Length("content_url")).filter(l__gt=2048).exists():
        raise RuntimeError("Post.content_url longer than 2048 characters")
    if Community.objects.annotate(l=Length("slug")).filter(l__gt=191).exists():
        raise RuntimeError("Community.slug longer than 191 characters")
    if User.objects.annotate(l=Length("username")).filter(l__gt=191).exists():
        raise RuntimeError("User.username longer than 191 characters")


def populate_slugs(apps, schema_editor):
    Post = apps.get_model("core", "Post")
    for post in Post.objects.all():
        post.slug = slugify(post.title)[:191]
        post.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0031b_schema_updates"),
    ]

    operations = [
        migrations.RunPython(check_lengths, migrations.RunPython.noop),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
