# Generated by Django 5.2.5 on 2025-09-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031a_populate_slugs"),
    ]

    operations = []
