# Generated by Django 5.2.5 on 2025-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031c_remove_post_image_remove_post_image_thumb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
