# Generated by Django 5.2.5 on 2025-09-09 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "post"), ("comment", "comment")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                ("value", models.SmallIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("target_type__in", ["post", "comment"])),
                        name="vote_valid_target_type",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "target_type", "target_id"),
                        name="uniq_vote_user_target",
                    ),
                ],
            },
        ),
    ]
